#!/bin/sh

#gpg --keyserver-options autokey-retrive --verify archlinux-2022.04.01-x86_64.iso.sig

#pacmon-key -v archlinux-verion-x86_64.iso.sig
loadkeys fr-latin1
#ls /sys/firmware/efi/efivars

timedatectl set-ntp true

parted /dev/sda mklabel msdos mkpart primary 0% 100%

mkfs.ext4 /dev/sda1
mount /dev/sda1 /mnt

#pacstrap /mnt base linux linux-firmware

#mount /dev/sda1 /mnt

#genfstab -U /mnt >> /mnt/etc/fstab

#arch-chroot /mnt

#ln -sf /usr/share/zoneinfo/France/Paris /etc/localtime

#hwclock --systohc

#locale-gen
#/etc/locale.conf
#/etc/vconsole.conf

#mkinitcpio -P

#passwd

