#!/bin/sh

#gpg --keyserver-options autokey-retrive --verify archlinux-2022.04.01-x86_64.iso.sig

#pacmon-key -v archlinux-verion-x86_64.iso.sig
loadkeys fr-latin1
#ls /sys/firmware/efi/efivars

echo "coucou"
timedatectl set-ntp true
echo "before parted"

parted /dev/sda mklabel msdos 
parted /dev/sda mkpart primary 0% 100%

echo "after parted"
mkfs.ext4 /dev/sda1
mount /dev/sda1 /mnt

pacstrap /mnt base linux linux-firmware

mount /dev/sda1 /mnt

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt /bin/bash -c 'ln -sf /usr/share/zoneinfo/France/Paris /etc/localtime; hwclock --systohc; locale-gen; touch /etc/locale.conf; echo "LANG=en_US.UTF-8" > /etc/locale.conf; touch /etc/vconsole.conf; echo "KEYMAP=fr-latin1" > /etc/vconsole.conf; touch /etc/hostname; echo "3IBC-crichard-pbisset" > /etc/hostname; mkinitcpio -P;'
echo "Entrez la commande passwd pour creer votre mot de passe"
